name: Build and Package with Inno Setup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up OpenSSL
      run: choco install openssl

    - name: Generate self-signed certificate
      run: |
        openssl req -x509 -newkey rsa:2048 -keyout yourdomain.key -out yourdomain.crt -days 365 -nodes -subj "/CN=YourApp"
        openssl pkcs12 -export -out yourdomain.pfx -inkey yourdomain.key -in yourdomain.crt -passout pass:yourpassword
    
    - name: Install Windows SDK
      run: choco install windows-sdk-10.1
      
    - name: Install Inno Setup
      run: |
        choco install innosetup -y
        echo "C:\Program Files (x86)\Inno Setup 6" >> $GITHUB_PATH

    - name: Compile Inno Setup Script
      run: |
        ISCC.exe "${env:GITHUB_WORKSPACE}\innosetup\install.iss"
        
    - name: Upload compiled EXE file
      uses: actions/upload-artifact@v4
      with:
        name: MyXinLiJianKang-installer
        path: "D:/a/phpenv/phpenv/MyXinLiJianKang-0.1.exe"