name: Build and Package with Inno Setup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Inno Setup
      run: |
        choco install innosetup -y
        echo "C:\Program Files (x86)\Inno Setup 6" >> $GITHUB_PATH

    - name: Display GITHUB_WORKSPACE
      run: echo "Code is downloaded to ${env:GITHUB_WORKSPACE}"

    - name: Compile Inno Setup Script
      run: |
        ISCC.exe /DMyAppSourceDir="${env:GITHUB_WORKSPACE}" /DMyAppVersion="0.2" "${env:GITHUB_WORKSPACE}\innosetup\install.iss"
        
    - name: Upload compiled EXE file
      uses: actions/upload-artifact@v2
      with:
        name: MyXinLiJianKang-0.2-installer
        path: ${env:GITHUB_WORKSPACE}\MyXinLiJianKang-0.2.exe