name: Build and Package with Inno Setup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Windows SDK
      run: choco install windows-sdk-10.1
      
    - name: Find signtool.exe path
      run: |
        $signtoolPath = Get-ChildItem -Recurse -Path "C:\Program Files (x86)\Windows Kits\10\bin" -Filter "signtool.exe" | Select-Object -First 1 -ExpandProperty FullName
        if ($signtoolPath) {
          echo "signtool.exe found at $signtoolPath"
        } else {
          echo "signtool.exe not found"
        }

    - name: Set up OpenSSL
      run: choco install openssl

    - name: Generate self-signed certificate
      run: |
        openssl req -x509 -newkey rsa:2048 -keyout D:/a/phpenv/phpenv/yourdomain.key -out D:/a/phpenv/phpenv/yourdomain.crt -days 365 -nodes -subj "/CN=YourApp"
        openssl pkcs12 -export -out D:/a/phpenv/phpenv/yourdomain.pfx -inkey D:/a/phpenv/phpenv/yourdomain.key -in D:/a/phpenv/phpenv/yourdomain.crt -passout pass:yourpassword
    


    - name: Install Inno Setup
      run: |
        choco install innosetup -y
        echo "C:\Program Files (x86)\Inno Setup 6" >> $GITHUB_PATH

    - name: Compile Inno Setup Script
      run: |
        ISCC.exe "${env:GITHUB_WORKSPACE}\innosetup\install.iss"
        
    - name: Upload compiled EXE file
      uses: actions/upload-artifact@v4
      with:
        name: MyXinLiJianKang-installer
        path: "D:/a/phpenv/phpenv/MyXinLiJianKang-0.1.exe"